### ISSUE TITLE
All class scoped variables should have a prefix of "m_"

### ISSUE THREAD

**Issue by abhishek-elastics** [dalance/svlint#178]
All class member variables should begin with "m_". Conversely, if a variable begins with "m_", it should be a class scoped variable and not a method scoped variable

# Pass
```
class abc extends uvm_sequence_item;
   int m_foo;
   string m_bar;

   function void dont_care();
     int foo;
     int bar;
   endfunction: dont_care
endclass: abc
```

# Fail
```
class abc extends uvm_sequence_item;
  int m_foo;
  string bar;                               // Class scoped variable doesn't begin with "m_"
  
  function void dont_care();
    int m_foo;                              // Non-class (local) variable begins with "m_"
    int bar;
  endfunction: dont_care
endclass: abc
```

**Comment by DaveMcEwan** [comment]
@abhishek-elastics I think this could be addressed by adding some rules to #195.
I'm thinking of these 4 rules: `re_(forbidden|required)_(class|function)_var`
Is this something you'd like to add to my PR?

**Comment by abhishek-elastics** [comment]
Hey @DaveMcEwan That would be great. method could be a ```task``` as well. Although I'm not sure by what you meant by "add"? Do you want me to commit to your PR?

**Comment by DaveMcEwan** [comment]
I've just had a go at implementing them myself on a derived branch `reRules-dev`.
Would you like to test it to see if it fits your needs?
If you're satisfied, then I can easily merge it into #195.

1. Clone and build my dev branch.
```
git clone git@github.com:DaveMcEwan/svlint.git svlint-TEST178
cd svlint-TEST178
git checkout reRules-dev
cargo build
```

2. Configure the rexeges in a `test178.toml` file with something like this:
```toml
[option]
#re_forbidden_var_class = ""
re_forbidden_var_classmethod = "^m_"
re_required_var_class = "^m_[a-z]+[a-z0-9]*$"
#re_required_var_classmethod = ""

[rules]
#re_forbidden_var_class = true
re_forbidden_var_classmethod = true
re_required_var_class = true
#re_required_var_classmethod = true
```

3. Run svlint on some of your files like this:
```
SVLINT_CONFIG=test178.toml cargo run --bin=svlint -- path/to/file.sv
```
